apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: placewaifu
  namespace: flux-system
spec:
  interval: 10m
  path: "./deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: placewaifu
