# apiVersion: notification.toolkit.fluxcd.io/v1beta3
# kind: Provider
# metadata:
#   name: grafana
#   namespace: monitoring
# spec:
#   type: grafana
#   address: "http://prometheus-stack-grafana.monitoring/api/annotations"
#   secretRef:
#     name: prometheus-stack-grafana
# ---
# apiVersion: notification.toolkit.fluxcd.io/v1beta3
# kind: Alert
# metadata:
#   name: grafana
#   namespace: monitoring
# spec:
#   providerRef:
#     name: grafana
#   eventSeverity: info
#   eventSources:
#     - kind: GitRepository
#       name: "*"
#       namespace: flux-system
