apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: umami
  namespace: analytics
spec:
  interval: 10m
  chart:
    spec:
      chart: umami
      version: "4.7.7"
      sourceRef:
        kind: HelmRepository
        name: umami
        namespace: analytics
      interval: 10m
  values:
    database:
      databaseUrlKey: url
      existingSecret: umami-postgres-url
    replicaCount: 1
    podLabels:
      app: umami
    revisionHistoryLimit: 2
    serviceAccount:
      create: true
    postgresql:
      # use cnpg
      enabled: false
    umami:
      appSecret:
        existingSecret: umami-app-secret
      trackerScriptName: selfhosted-umami
    # ingress enabled in monitoring/umami
