# cloudflare origin for umami
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-origin-xetera-dev
  namespace: analytics
type: kubernetes.io/tls
spec:
  itemPath: "vaults/k8s-cloud/items/cloudflare-origin:xetera.dev"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami
  namespace: analytics
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`overtime-contingency.xetera.dev`)
      priority: 10
      services:
        - name: umami
          port: 3000
      middlewares:
        - name: ingress-cloudflare-only@kubernetescrd
  tls:
    options:
      name: cloudflare-mtls@kubernetescrd
    secretName: cloudflare-origin-xetera-dev
