apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-forgejo"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: forgejo-admin-credentials
  namespace: forgejo
spec:
  itemPath: "vaults/k8s-cloud/items/forgejo-admin-credentials"
