# namespace: ingress
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-origin-xetera-dev
  namespace: monitoring
type: kubernetes.io/tls
spec:
  itemPath: "vaults/k8s-cloud/items/cloudflare-origin:xetera.dev"
