apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amnezia-wg-easy-config
  namespace: vpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "local-path"
