apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: amnezia-wg-easy
  namespace: vpn
spec:
  selector:
    matchLabels:
      app: amnezia-wg-easy
  podMetricsEndpoints:
    - port: http
