apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: monitoring
spec:
  interval: 60m
  chart:
    spec:
      chart: signoz
      version: "0.110.0"
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: monitoring
      interval: 24h
  values:
    fullnameOverride: signoz
    global:
      cloud: hcloud
