apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signoz-tailscale
  namespace: monitoring
spec:
  defaultBackend:
    service:
      name: signoz
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - signoz
