apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-k8s-infra
  namespace: monitoring
spec:
  interval: 60m
  chart:
    spec:
      chart: k8s-infra
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: monitoring
      interval: 24h
  values:
    global:
      # Cloud provider configuration
      cloud: "other"
      # Cluster identification
      clusterName: "production"
      deploymentEnvironment: "production"

    # Configure to send to self-hosted SigNoz
    otelCollectorEndpoint: "signoz-otel-collector.monitoring.svc.cluster.local:4317"
    otelInsecure: true

    # Presets - enable comprehensive k8s monitoring
    presets:
      # Collect logs from all containers
      logsCollection:
        enabled: true
        includeCollectorLogs: false

      # Collect host metrics from nodes
      hostMetrics:
        enabled: true

      # Collect kubelet metrics
      kubeletMetrics:
        enabled: true

      # Collect cluster metrics from k8s API
      clusterMetrics:
        enabled: true

      # Kubernetes attributes processor
      kubernetesAttributes:
        enabled: true
