apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-k8s-infra
  namespace: monitoring
spec:
  interval: 60m
  chart:
    spec:
      chart: k8s-infra
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: monitoring
      interval: 24h
  values:
    global:
      cloud: "hcloud"

    # Configure to send to self-hosted SigNoz
    otelCollectorEndpoint: "signoz-otel-collector.monitoring.svc.cluster.local:4317"
    otelInsecure: true

    # Presets - enable comprehensive k8s monitoring
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: false

      hostMetrics:
        enabled: true

      kubeletMetrics:
        enabled: true

      # Collect cluster metrics from k8s API
      clusterMetrics:
        enabled: true

      # Kubernetes attributes processor
      kubernetesAttributes:
        enabled: true

    # Custom configuration for deployment collector (PostgreSQL monitoring)
    otelDeployment:
      enabled: true
      # Environment variables for PostgreSQL credentials
      additionalEnvs:
        POSTGRES_USER:
          valueFrom:
            secretKeyRef:
              name: postgres-user-signoz
              key: username
        POSTGRES_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: postgres-user-signoz
              key: password
      config:
        receivers:
          # PostgreSQL receiver
          postgresql:
            endpoint: postgres-rw.cnpg-system.svc.cluster.local:5432
            transport: tcp
            username: ${env:POSTGRES_USER}
            password: ${env:POSTGRES_PASSWORD}
            databases:
              - postgres
            collection_interval: 30s
            tls:
              insecure: true
        processors:
          batch:
            timeout: 5s
            send_batch_size: 1024
        exporters:
          otlp:
            endpoint: signoz-otel-collector.monitoring.svc.cluster.local:4317
            tls:
              insecure: true
        service:
          pipelines:
            metrics:
              receivers: [postgresql]
              processors: [batch]
              exporters: [otlp]
