apiVersion: apps/v1
kind: Deployment
metadata:
  name: me
spec:
  selector:
    matchLabels:
      app: me
  template:
    metadata:
      labels:
        app: me
    spec:
      initContainers:
        - name: me-migrate
          image: xetera/me:latest
          imagePullPolicy: IfNotPresent
          command: ["npx", "prisma", "migrate", "deploy"]
          volumeMounts:
            - name: me-data
              mountPath: /app/data
      containers:
        - name: me
          image: xetera/me:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 3000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.monitoring.svc.cluster.local:4318"
          volumeMounts:
            - name: me-data
              mountPath: /app/data
            - name: me-config
              mountPath: /app/config.toml
              subPath: config.toml
      volumes:
        - name: me-data
          emptyDir: {}
        - name: me-config
          configMap:
            name: me
---
apiVersion: v1
kind: Service
metadata:
  name: me
spec:
  selector:
    app: me
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: me
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k8s-me.xetera.dev`)
      priority: 10
      services:
        - name: me
          port: 80
      middlewares:
        - name: ingress-cloudflare-only@kubernetescrd
  tls:
    options:
      name: cloudflare-mtls@kubernetescrd
    secretName: cloudflare-origin-xetera-dev
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: me
spec:
  podMetricsEndpoints:
    - interval: 5s
      port: "3000"
  selector:
    matchLabels:
      app: me
