apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: ingress
spec:
  interval: 60m
  chart:
    spec:
      chart: authelia
      version: "0.10.10"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: ingress
      interval: 60m
  values:
    configMap:
      storage:
        postgres:
          enabled: true
          address: tcp://postgres-rw.cnpg-system.svc.cluster.local:5432
          database: authelia
          schema: public
          username: authelia
