apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: ingress
spec:
  interval: 60m
  chart:
    spec:
      chart: authelia
      version: "0.10.14"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: ingress
      interval: 60m
  values:
    configMap:
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
      telemetry:
        metrics:
          enabled: true
          port: 9090
      session:
        cookies:
          - subdomain: auth
            domain: xetera.dev
      authentication_backend:
        file:
          enabled: true
          path: /data/authelia/users_database.yml
          password:
            algorithm: argon2
      storage:
        postgres:
          enabled: true
          address: tcp://postgres-rw.cnpg-system.svc.cluster.local:5432
          database: authelia
          schema: public
          username: authelia
          password:
            secret_name: postgres-user-authelia
            path: password
