apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-proxy
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake-proxy
  template:
    metadata:
      labels:
        app: snowflake-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: snowflake-proxy
          image: thetorproject/snowflake-proxy:latest
          imagePullPolicy: Always
          args:
            - -metrics
            - -metrics-address
            - "0.0.0.0"
            - -ephemeral-ports-range
            - "32768:60999"
          ports:
            - name: metrics
              containerPort: 9999
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 512Mi
