apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-actions
  namespace: actions-runner-system
spec:
  interval: 60m
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.23.7"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: actions-runner-system
      interval: 24h
  values:
    authSecret:
      name: github-app
