apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  itemPath: "vaults/k8s-cloud/items/tailscale-operator-oauth"
  # client_id, client_secret
