apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  interval: 24h
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.142.0"
      sourceRef:
        kind: HelmRepository
        name: otel-collector
        namespace: monitoring
      interval: 24h
  values:
    extraEnvs:
      - name: DASH0_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: otel-collector-credentials
            key: token
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
    mode: deployment
    fullnameOverride: otel-collector
    clusterRole:
      create: true
      rules:
        - apiGroups: [""]
          resources: ["nodes", "nodes/metrics", "nodes/stats", "services", "endpoints", "pods"]
          verbs: ["get", "list", "watch"]
        - apiGroups: [""]
          resources: ["configmaps"]
          verbs: ["get"]
        - apiGroups: ["discovery.k8s.io"]
          resources: ["endpointslices"]
          verbs: ["get", "list", "watch"]
        - nonResourceURLs: ["/metrics"]
          verbs: ["get"]
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        prometheus:
          config:
            scrape_configs:
              # Kubernetes service discovery for pods
              - job_name: 'kubernetes-pods'
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  # Only scrape pods with prometheus.io/scrape=true annotation
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                    action: keep
                    regex: true
                  # Use prometheus.io/path annotation for metrics path (default /metrics)
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                    action: replace
                    target_label: __metrics_path__
                    regex: (.+)
                  # Use prometheus.io/port annotation for metrics port
                  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                    action: replace
                    regex: ([^:]+)(?::\d+)?;(\d+)
                    replacement: $1:$2
                    target_label: __address__
                  # Add pod labels
                  - action: labelmap
                    regex: __meta_kubernetes_pod_label_(.+)
                  - source_labels: [__meta_kubernetes_namespace]
                    action: replace
                    target_label: kubernetes_namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    action: replace
                    target_label: kubernetes_pod_name

      processors:
        batch:
          timeout: 10s
          send_batch_size: 1024

      exporters:
        otlp/dash0:
          endpoint: ingress.eu-west-1.aws.dash0.com:4317
          headers:
            Authorization: "Bearer ${DASH0_AUTH_TOKEN}"

      extensions:
        health_check:
          endpoint: 0.0.0.0:13133

      service:
        extensions: [health_check]
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/dash0]
          metrics:
            receivers: [otlp, prometheus]
            processors: [batch]
            exporters: [otlp/dash0]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/dash0]
