---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-s3-backups
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/wasabi-s3-postgres-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-umami
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-umami"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-developer
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-developer"
---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: cnpg-system
spec:
  images:
    - major: 17
      image: ghcr.io/clevyr/cloudnativepg-timescale:17.4
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cnpg-system
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 17
  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION timescaledb;
  storage:
    size: 10Gi
    storageClass: local-path
  managed:
    roles:
      - name: umami
        comment: "plausible analytics role"
        login: true
        superuser: false
        passwordSecret:
          name: umami-user-postgres

      - name: developer
        ensure: present
        comment: "role for development only"
        login: true
        superuser: false
        passwordSecret:
          name: developer-password

  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://kubernetes-postgres-backup/
      endpointURL: https://s3.eu-central-2.wasabisys.com
      s3Credentials:
        accessKeyId:
          name: postgres-s3-backups
          key: access_key
        secretAccessKey:
          name: postgres-s3-backups
          key: secret_key
  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    shared_preload_libraries:
      - timescaledb
      - pg_stat_statements
  monitoring:
    enablePodMonitor: true
---
# Umami database
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: umami-db
  namespace: cnpg-system
spec:
  name: umami
  owner: umami
  cluster:
    name: postgres
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
  namespace: cnpg-system
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": postgres
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
  namespace: cnpg-system
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cnpg-alerts
  namespace: cnpg-system
spec:
  groups:
    - name: cnp-default.rules
      rules:
        - alert: LongRunningTransaction
          annotations:
            description: Pod {{ $labels.pod }} is taking more than 5 minutes (300 seconds) for a query.
            summary: A query is taking longer than 5 minutes.
          expr: |-
            cnpg_backends_max_tx_duration_seconds > 300
          for: 1m
          labels:
            severity: warning
        - alert: BackendsWaiting
          annotations:
            description: Pod {{ $labels.pod  }} has been waiting for longer than 5 minutes
            summary: If a backend is waiting for longer than 5 minutes
          expr: |-
            cnpg_backends_waiting_total > 300
          for: 1m
          labels:
            severity: warning
        - alert: PGDatabaseXidAge
          annotations:
            description: Over 300,000,000 transactions from frozen xid on pod {{ $labels.pod  }}
            summary: Number of transactions from the frozen XID to the current one
          expr: |-
            cnpg_pg_database_xid_age > 300000000
          for: 1m
          labels:
            severity: warning
        - alert: PGReplication
          annotations:
            description: Standby is lagging behind by over 300 seconds (5 minutes)
            summary: The standby is lagging behind the primary
          expr: |-
            cnpg_pg_replication_lag > 300
          for: 1m
          labels:
            severity: warning
        - alert: LastFailedArchiveTime
          annotations:
            description: Archiving failed for {{ $labels.pod }}
            summary: Checks the last time archiving failed. Will be < 0 when it has not failed.
          expr: |-
            (cnpg_pg_stat_archiver_last_failed_time - cnpg_pg_stat_archiver_last_archived_time) > 1
          for: 1m
          labels:
            severity: warning
        - alert: DatabaseDeadlockConflicts
          annotations:
            description: There are over 10 deadlock conflicts in {{ $labels.pod }}
            summary: Checks the number of database conflicts
          expr: |-
            cnpg_pg_stat_database_deadlocks > 10
          for: 1m
          labels:
            severity: warning
        - alert: ReplicaFailingReplication
          annotations:
            description: Replica {{ $labels.pod }} is failing to replicate
            summary: Checks if the replica is failing to replicate
          expr: |-
            cnpg_pg_replication_in_recovery > cnpg_pg_replication_is_wal_receiver_up
          for: 1m
          labels:
            severity: warning
