apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: me
  namespace: flux-system
spec:
  # controlled by webhooks
  interval: 60m
  url: https://github.com/xetera/me
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: me
  namespace: flux-system
spec:
  interval: 10m
  path: "./deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: me
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: me
  namespace: flux-system
spec:
  type: github
  address: https://github.com/xetera/me
  secretRef:
    name: github-pat
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: me
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
    - "package"
  secretRef:
    name: flux-webhook-token
  resources:
    - kind: GitRepository
      name: me
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: me
  namespace: flux-system
spec:
  providerRef:
    name: me
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
