apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beyla
  namespace: monitoring
spec:
  interval: 60m
  chart:
    spec:
      chart: beyla
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: beyla
        namespace: monitoring
      interval: 60m
  # values:
  #   beyla:
  #     enabled: true
  #     namespace: monitoring
  #     image:
  #       repository: ghcr.io/beyla/beyla
  #       tag: v0.1.0
  #       pullPolicy: IfNotPresent
