---
# namespace: ingress
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-origin-xetera-dev
  namespace: ingress
type: kubernetes.io/tls
spec:
  itemPath: "vaults/k8s-cloud/items/cloudflare-origin:xetera.dev"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-mtls
  namespace: ingress
spec:
  itemPath: "vaults/k8s-cloud/items/cloudflare-mtls"
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: cloudflare-mtls
  namespace: ingress
spec:
  clientAuth:
    clientAuthType: RequireAndVerifyClientCert
    secretNames:
      - cloudflare-mtls
  minVersion: VersionTLS12
