apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/kube-prometheus-stack"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: umami
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/umami"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: analytics
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/tailscale"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: tailscale
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/cloudnative-pg"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cnpg-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1password-connect
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/1password"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: 1password
