apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: shoal
  namespace: flux-system
spec:
  image: ghcr.io/xetera/shoal
  interval: 30m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: shoal
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: shoal
  filterTags:
    pattern: '^v(?P<version>\d+\.\d+\.\d+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=0.1.0'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: shoal
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: shoal
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        deploy: {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./deploy
    strategy: Setters
