apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: shoal
  namespace: flux-system
spec:
  image: ghcr.io/xetera/shoal
  interval: 30m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: shoal
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: shoal
  filterTags:
    pattern: '^(?P<ts>\d+)-[a-f0-9]+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: shoal
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: shoal
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        deploy: {{range .Changed.Changes}}{{println .OldValue "->" .NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./deploy
    strategy: Setters
