apiVersion: v1
kind: Service
metadata:
  name: tls-client-api
  namespace: default
spec:
  selector:
    app: tls-client-api
  ports:
    - port: 8080
      targetPort: 8080
      name: proxy
    - port: 8081
      targetPort: 8081
      name: health
    - port: 8082
      targetPort: 8082
      name: metrics
