apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cnpg-system
  # annotations:
  #   kustomize.toolkit.fluxcd.io/force: enabled
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 17
  bootstrap:
    # recovery:
    #   backup:
    #     name: postgres-20250304202332
    # backupSource:
    #   barmanObjectStore:
    #     destinationPath: s3://kubernetes-postgres-backup/
    #     endpointURL: https://s3.eu-central-2.wasabisys.com
    #     s3Credentials:
    #       accessKeyId:
    #         name: postgres-s3-backups
    #         key: access_key
    #       secretAccessKey:
    #         name: postgres-s3-backups
    #         key: secret_key
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION timescaledb;
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
  managed:
    roles:
      - name: signoz
        comment: "signoz monitoring user"
        login: true
        superuser: false
        inRoles:
          - pg_monitor
        passwordSecret:
          name: postgres-user-signoz
      - name: umami
        comment: "plausible analytics role"
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user-umami
      - name: me
        comment: "me service role"
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user-me
      - name: developer
        ensure: present
        comment: "role for development only"
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user-developer
      - name: authelia
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user-authelia
      - name: smsai
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user-smsai
      - name: wedding
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user-wedding
      - name: weblate
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user-weblate
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 800m
      memory: 1024Mi
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://kubernetes-postgres-backup/
      endpointURL: https://s3.eu-central-2.wasabisys.com
      s3Credentials:
        accessKeyId:
          name: postgres-s3-backups
          key: access_key
        secretAccessKey:
          name: postgres-s3-backups
          key: secret_key
      wal:
        maxParallel: 8
        compression: gzip
  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    shared_preload_libraries:
      - timescaledb
      - pg_stat_statements
  monitoring:
    enablePodMonitor: true
