apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
  namespace: cnpg-system
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": postgres
  podMetricsEndpoints:
    - port: metrics
