---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-s3-backups
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/wasabi-s3-postgres-credentials"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-umami
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-umami"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-me
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-me"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-developer
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-developer"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-authelia
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-authelia"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-askergpt
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-askergpt"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-wedding
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-wedding"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-user-weblate
  namespace: cnpg-system
spec:
  itemPath: "vaults/k8s-cloud/items/postgres-user-weblate"
