apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: 1password
spec:
  interval: 60m
  chart:
    spec:
      chart: connect
      version: "1.17.1"
      sourceRef:
        kind: HelmRepository
        name: connect
        namespace: 1password
      interval: 60m
  values:
    operator:
      create: true
      token:
        name: 1password-token
        key: token
    connect:
      credentialsKey: 1password-credentials.json
      credentialsName: 1password-credentials
      dataVolume:
        type: local-path
