apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: pandemic
  namespace: flux-system
spec:
  type: github
  address: https://github.com/xetera/pandemic
  secretRef:
    name: github-pat
