apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: me
  namespace: flux-system
spec:
  # controlled by webhooks
  interval: 60m
  url: ssh://git@github.com/Xetera/me
  ref:
    branch: main
  secretRef:
    name: flux-system
