apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: offload
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  ensure-users.js: |
    const adminDb = db.getSiblingDB('admin');
    adminDb.createUser({user: "root", pwd: "this_db_is_never_exposed_publicly", roles:[{role: "userAdminAnyDatabase" , db:"admin"}]});
