apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: offload
spec:
  storageClassName: local-path
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
