name: Build Containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/build-containers.yaml
env:
  tls-client-api-version: 1.8.0
  amnezia-wg-easy-version: 14

jobs:
  build-tls-client-api:
    # preventing cross-compilation
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push tls-client-api
        uses: docker/build-push-action@v6
        with:
          context: docker/tls-client-api
          file: docker/tls-client-api/Dockerfile
          build-args: version=${{env.tls-client-api-version}}
          # my cluster runs on arm64 nodes exclusively
          platforms: linux/arm64
          push: true
          outputs: type=docker
          tags: |
            ghcr.io/xetera/tls-client-api:${{ env.tls-client-api-version }}
            ghcr.io/xetera/tls-client-api:latest
  build-amnezia-wg-easy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push amnezia-wg-easy
        uses: docker/build-push-action@v6
        with:
          context: docker/amnezia-wg-easy
          file: docker/amnezia-wg-easy/Dockerfile
          build-args: version=${{env.amnezia-wg-easy-version}}
          platforms: linux/arm64
          push: true
          outputs: type=docker
          tags: |
            ghcr.io/xetera/amnezia-wg-easy:${{ env.amnezia-wg-easy-version }}
            ghcr.io/xetera/amnezia-wg-easy:latest
          # cache-from: |
          #   type=registry,ref=ghcr.io/xetera/tls-client-api:${{ env.tls-client-api-version }}
          #   type=registry,ref=ghcr.io/xetera/tls-client-api:latest
          # cache-to: type=registry,ref=ghcr.io/xetera/tls-client-api:${{ env.tls-client-api-version }},mode=max
